<a href="https://colab.research.google.com/github/JuanCaG8a/Repositorio-Metodos-1/blob/main/AlgebraLineal.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

1) Muestre el n-esimos+1 termino de las siguientes relaciones recursivas:$$x_{n+1} = 4x_n−x^{2}_n,    x_0= 4sin^2θ$$, conduce a: $$x_{n+1}= 4sin^2(2^{n+1}θ),    θ ∈ [0,π/2].$$ $$x_{n+1}= 4x_n−4x^2_n,    x_0=sin^{2}θ $$, conduce a: $$ x_{n+1}=sin^2(2^{n+1}θ),    θ∈[0,π/2]$$

3) En Python, implemente una clase para solucionar sistemas lineales. El constructor de clase debe recibir la matriz y el vector independiente.  El primer metodo de clase resuelve el sistema usando el metodo de Jacobi, y el segundo metodo resuelve el sistema usando el metodo de Gaus-Seidel.  En la pantalla debe aparecer el numero de iteraciones necesarias para resolver el problema

In [8]:
class SistemasLineales:
    def __init__(self, A, b, tol=1e-6, max_iter=1000):
        self.A = np.array(A, dtype=float)
        self.b = np.array(b, dtype=float)
        self.tol = tol
        self.max_iter = max_iter

    def metodo_jacobi(self):
        x = np.zeros_like(self.b)
        D = np.diag(self.A)
        R = self.A - np.diagflat(D)

        iteraciones = 0
        for i in range(self.max_iter):
            x_new = (self.b - np.dot(R, x)) / D
            if np.linalg.norm(x_new - x, ord=np.inf) < self.tol:
                break
            x = x_new
            iteraciones += 1

        print(f"Jacobi: Sistema resuelto en {iteraciones} iteraciones.")
        return x

    def metodo_gauss_seidel(self):
        x = np.zeros_like(self.b)
        iteraciones = 0

        for i in range(self.max_iter):
            x_new = np.copy(x)
            for j in range(len(self.b)):
                suma = sum(self.A[j][k] * x_new[k] if k < j else self.A[j][k] * x[k] for k in range(len(self.b)))
                x_new[j] = (self.b[j] - suma + self.A[j][j] * x[j]) / self.A[j][j]

            if np.linalg.norm(x_new - x, ord=np.inf) < self.tol:
                break
            x = x_new
            iteraciones += 1

        print(f"Gauss-Seidel: Sistema resuelto en {iteraciones} iteraciones.")
        return x

# Ejemplo de uso
A = [[4, -1, 0, 0],
     [-1, 4, -1, 0],
     [0, -1, 4, -1],
     [0, 0, -1, 3]]

b = [15, 10, 10, 10]

sistema = SistemasLineales(A, b)

# Solucion usando Jacobi
solucion_jacobi = sistema.metodo_jacobi()
print("Solución usando Jacobi:", solucion_jacobi)

# Solucion usando Gauss-Seidel
solucion_gauss_seidel = sistema.metodo_gauss_seidel()
print("Solución usando Gauss-Seidel:", solucion_gauss_seidel)


Jacobi: Sistema resuelto en 18 iteraciones.
Solución usando Jacobi: [4.99999939 4.99999899 4.99999886 4.99999912]
Gauss-Seidel: Sistema resuelto en 10 iteraciones.
Solución usando Gauss-Seidel: [4.99999918 4.99999941 4.99999972 4.99999991]


5) Muestre con detalle que la sustitucion hacia adelante se expresa como:
$$x_i = \frac{b_i-\sum_{j=0}^{i-1}A_{ij}x_j}{A_{ii}}$$

8)   Implemente la descomposicion LU para factorizar la siguiente matriz A = LU.

    4    -2    1  	  1    0    0      4    -2     1
A =     20   -7   12   =    5    1    0      0     3     7   
    -8   13   17       -2    3    1      0     0    -2  

In [9]:
def LU(A):
    n = len(A)
    L = np.eye(n)
    U = np.zeros((n, n))

    for i in range(n):
        for k in range(i, n):
            U[i, k] = A[i, k] - sum(L[i, j] * U[j, k] for j in range(i))

        for k in range(i + 1, n):
            L[k, i] = (A[k, i] - sum(L[k, j] * U[j, i] for j in range(i))) / U[i, i]

    return L, U

A = np.array([[4, -2, 1],
              [20, -7, 12],
              [-8, 13, 17]], dtype=float)


L, U = LU(A)


print("Matriz L:")
print(L)
print("Matriz U:")
print(U)


Matriz L:
[[ 1.  0.  0.]
 [ 5.  1.  0.]
 [-2.  3.  1.]]
Matriz U:
[[ 4. -2.  1.]
 [ 0.  3.  7.]
 [ 0.  0. -2.]]


12) Usando los m etodos de Newton-Raphson y descenso del gradiente, encuentre la solucion de los siguientes sistemas de ecuaciones no lineales:
$$ ln(x^2_1+x^2_2)−sin(x_1x_2)   =ln(2) +ln(π)$$  $$e^{x_1−x_2}+cos(x_1x_2)   =   0 $$
Use $$x^{(0)} = (2,2)$$
$$6x_1-2cos(x_2x_3)-1 = 0, $$
$$9x_2 + \sqrt{x_1^2 + sin(x_3) + 1.06 } + 0.9 = 0,  $$
$$ 60x_3 + 3e^{-x_1x_2} + 10π - 3 = 0. $$
Use $$x^{(0)} = (0,0,0)$$


In [5]:
def sistema1(vars):
    x1, x2 = vars
    f1 = np.log(x1**2 + x2**2) - np.sin(x1 * x2) - np.log(2) - np.log(np.pi)
    f2 = np.exp(x1 - x2) + np.cos(x1 * x2)
    return [f1, f2]

def sistema2(vars):
    x1, x2, x3 = vars
    f1 = 6*x1 - 2*np.cos(x2 * x3) - 1
    f2 = 9*x2 + np.sqrt(x1**2 + np.sin(x3) + 1.06) + 0.9
    f3 = 60*x3 + 3*np.exp(-x1 * x2) + 10*np.pi - 3
    return [f1, f2, f3]

def jacobiano_sistema1(x1, x2):
    j11 = (2*x1) / (x1**2 + x2**2) - x2 * np.cos(x1 * x2)
    j12 = (2*x2) / (x1**2 + x2**2) - x1 * np.cos(x1 * x2)
    j21 = np.exp(x1 - x2) - x2 * np.sin(x1 * x2)
    j22 = -np.exp(x1 - x2) - x1 * np.sin(x1 * x2)

    return np.array([[j11, j12], [j21, j22]])

def newton_raphson_sistema1(x0, tol=1e-6, max_iter=100):
    x = np.array(x0)
    for i in range(max_iter):
        f = np.array(sistema1(x))
        J = jacobiano_sistema1(x[0], x[1])
        delta_x = np.linalg.solve(J, -f)
        x = x + delta_x
        if np.linalg.norm(delta_x) < tol:
            break
    return x


def jacobiano_sistema2(x1, x2, x3):
    j11 = 6
    j12 = 2*x3 * np.sin(x2 * x3)
    j13 = 2*x2 * np.sin(x2 * x3)

    j21 = x1 / np.sqrt(x1**2 + np.sin(x3) + 1.06)
    j22 = 9
    j23 = (np.cos(x3) / (2 * np.sqrt(x1**2 + np.sin(x3) + 1.06)))

    j31 = -3 * x2 * np.exp(-x1 * x2)
    j32 = -3 * x1 * np.exp(-x1 * x2)
    j33 = 60

    return np.array([[j11, j12, j13], [j21, j22, j23], [j31, j32, j33]])

def newton_raphson_sistema2(x0, tol=1e-6, max_iter=100):
    x = np.array(x0)
    for i in range(max_iter):
        f = np.array(sistema2(x))
        J = jacobiano_sistema2(x[0], x[1], x[2])
        delta_x = np.linalg.solve(J, -f)
        x = x + delta_x
        if np.linalg.norm(delta_x) < tol:
            break
    return x

x0_sistema1 = [2, 2]
x0_sistema2 = [0, 0, 0]


solution_newton_sistema1 = newton_raphson_sistema1(x0_sistema1)
solution_newton_sistema2 = newton_raphson_sistema2(x0_sistema2)

solution_newton_sistema1, solution_newton_sistema2


(array([1.77245385, 1.77245385]),
 array([ 0.49814468, -0.1996059 , -0.52882598]))

14)